import BorderColorIcon from '@mui/icons-material/BorderColor';
import DeleteForeverIcon from '@mui/icons-material/DeleteForever';
import { Divider, Grid, IconButton, ListItem, Typography } from "@mui/material";
import QuantityControlsContainer from "../../../common/quantityControls/QuantityControlsContainer";
import './ProductsListCart.css';

const ProductsListCart = ({product, handleAddProductToCart, deleteProduct, subtotal, cantidadRestar, cantidadProducto, cantidadAgregar}) => {
    return (
        <>
            <ListItem>
                <Grid
                    item
                    display={"flex"}
                    alignItems={"center"}
                    justifyContent={"center"}
                    sx={{
                        display: {xs: 'none', md:'flex'}
                    }}
                    md={2}
                >
                    <div
                        className="cartItem__img"
                    >
                        <img
                            src={product.thumbnail[0]} 
                            alt="Imagen del Producto" 
                        />
                    </div>
                </Grid>
                <Grid
                    container
                    item
                    xs={12}
                    md={10}
                >
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={12}
                        sm={6}
                    >
                        <Typography
                            variant="body1"
                            fontWeight={'bold'}
                            textAlign={'center'}
                            fontSize={20}
                        >
                            {product.name}
                        </Typography>
                    </Grid>
                    <Grid
                        item
                        sx={{
                            display: {xs: 'none', sm:'flex'}
                        }}
                        sm={2}
                    >
                    </Grid>
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={8}
                        sm={2}
                        sx={{textAlign:'center'}}
                    >
                        <Typography
                            variant="caption"
                            fontSize={12.5}
                        >
                            Precio por Unidad:
                        </Typography>
                    </Grid>
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={4}
                        sm={2}
                    >
                        <Typography
                            variant='body1'
                            fontSize={20}
                            fontWeight={'bold'}
                        >
                            ${product.price}
                        </Typography>
                    </Grid>
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={12}
                        sm={6}
                    >
                        <QuantityControlsContainer
                            cantidadRestar={cantidadRestar}
                            cantidadProducto={cantidadProducto}
                            cantidadAgregar={cantidadAgregar}
                            product={product}
                        />
                    </Grid>
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={6}
                        sm={1}
                    >
                        <IconButton
                            onClick={handleAddProductToCart}
                        >
                            <BorderColorIcon
                                color="secondary"
                                sx={{width:'35px', height:'35px'}}
                            />
                        </IconButton>
                    </Grid>
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={6}
                        sm={1}
                    >
                        <IconButton
                            onClick={deleteProduct}
                        >
                            <DeleteForeverIcon
                                color="error"
                                sx={{width:'40px', height:'40px'}}
                            />
                        </IconButton>
                    </Grid>
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={6}
                        sm={2}
                    >
                        <Typography>
                            Subtotal:
                        </Typography>
                    </Grid>
                    <Grid
                        item
                        display={"flex"}
                        alignItems={"center"}
                        justifyContent={"center"}
                        xs={6}
                        sm={2}
                    >
                        <Typography
                            variant="body1"
                            fontWeight={'bold'}
                            fontSize={22.5}
                        >
                            ${subtotal}
                        </Typography>
                    </Grid>
                </Grid>
            </ListItem>
            <Divider
                component={'li'}
            />
        </>
    );
};

export default ProductsListCart;